### PR TITLE
add github actions based ci

### PR DESCRIPTION
**Pull request by purificant**
This PR adds CI pipeline based on Github Actions.

Test are run in official python containers: python:3.6 through python:3.9.
A redis service container is provided for integration tests.

### CODE REVIEW

**Comment by AlecRosenbaum** [comment]
Thanks for the PR!

Why use github actions over the existing CircleCI integration?

**Comment by purificant** [comment]
Thank you for taking a look at the PR.

- CircleCI offers two sign in methods, via Github or Bitbucket. Sign in is required in order to be able to see the pipeline. Both of these methods request read and write permissions to a lot of potentially sensitive information such as private repositories and deploy keys. This kind of access might not be suitable for some users, or in compliance environments.
- Github Actions offer a more streamlined user experience for new contributors, CI is available immediately and executes on branch push after forking the repo, this is on contrast with CircleCI where additional setup is requires to run pipeline on the forked repo.

Because of more straightforward UX for contributors and because of more reasonable access scope, I believe it is worth considering Github Actions based CI alongside the existing integration on a trial basis.

Example CircleCI Github login access request:
circleci

**Comment by purificant** [comment]
Added code linting with black and running integration tests against different Redis versions.

**Comment by AlecRosenbaum** [comment]
Sounds good to me 👍 

Thanks for the contribution!

**Pull request merged**
