### PR TITLE
v0.12

### PR DESCRIPTION
**Pull request by jpmelos**
Going to release 0.12 before merging https://github.com/closeio/tasktiger/pull/185 and https://github.com/closeio/tasktiger/pull/186.

### CODE REVIEW

**Comment by jpmelos** [comment]
@thomasst any PRs you'd like to merge before we release 0.12? I see you have 3 PRs recently opened.

**Comment by thomasst** [comment]
- I just merged https://github.com/closeio/tasktiger/pull/180
- I am going to hold off with https://github.com/closeio/tasktiger/pull/181. It's not actually backwards compatible.
- I will finish https://github.com/closeio/tasktiger/pull/184 today if you want to wait until later.

There is another fix I wanted to do today or tomorrow. I'll see if I can squeeze it in today.

**Comment by jpmelos** [comment]
No worries, I can wait.

**Comment by thomasst** [comment]
FYI, this one is still pending a second review: https://github.com/closeio/tasktiger/pull/188

**Review by thomasst — COMMENTED** [review]
Should be ready to release now. Can you amend the changelog?

**Review by thomasst — APPROVED** [review]
Looks good. In the future I would probably just refer to the shortened commit hash in each change log entry to avoid linking to GitHub-specific stuff. No big deal though.

**Pull request merged**
